namespace: delivery-dev
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: delivery-demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
