apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delivery-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mrsddq/terraform-gitops-delivery-platform.git
    targetRevision: main
    path: kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: delivery-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
